# Check https://circleci.com/docs/2.0/language-go/ for more details
jobs:
  build:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
orbs:
  go: circleci/go@1.7.1
version: 2.1
workflows:
  main:
    jobs:
      - build
