# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.4
    steps:
      - checkout
      - run: go version
      - run:
          name: Run unit tests
          command: gotestsum --junitfile /tmp/test-results.xml -- -coverprofile=./coverage.out
      - run: go get github.com/mattn/goveralls
      - run:
          name: coveralls.io
          command: |
            if [ -z ${COVERALLS_TOKEN} ]; then
              echo "coveralls token isn't set, skipping"
            else
              goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
            fi
      - store_test_results:
          path: /tmp/test-results.xml
